# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

# builds.sr.ht - Build manifest
# https://man.sr.ht/builds.sr.ht/manifest.md

image: archlinux
sources:
  - https://git.sr.ht/~wombelix/cfn-custom-resource-aws-ssm-securestring
  - https://git.sr.ht/~wombelix/build-helper-scripts
secrets:
  - 5b076ab5-1361-4d71-905b-4ff8c836c62c
environment:
  GIT_MIRROR_SSH_KEY: ~/.ssh/5b076ab5-1361-4d71-905b-4ff8c836c62c
  GIT_MIRROR_GITHUB: git@github.com:wombelix/cfn-custom-resource-aws-ssm-securestring.git
  GIT_MIRROR_GITLAB: git@gitlab.com:wombelix/cfn-custom-resource-aws-ssm-securestring.git
  GIT_MIRROR_CODEBERG: git@codeberg.org:wombelix/cfn-custom-resource-aws-ssm-securestring.git
tasks:
  - mirror: |
      cd build-helper-scripts
      source git-mirror.sh
      cd ..

      cd cfn-custom-resource-aws-ssm-securestring

      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_GITHUB"
      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_GITLAB"
      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_CODEBERG"

triggers:
  - action: email
    condition: failure
    to: dominik@wombacher.cc
